const Constants = {
    endPointApi: 'https://api.myjson.com/bins/1fq8pm',
    provider: 'Provider:',
    universities: 'Universities:',
    subject: 'Subject:',
    childSubject: 'Child Subject',
    filterBy: 'Filter By:',
    sortBy: 'Sort By:',
    choose: 'Choose...',
    clear: 'Clear',
    totalCoursesFound: 'Total Courses Found',
    courseFoundBasedOnUserSearch: 'Course Found Based On Search',
    nextSessionLast: 'Next Session Date(nearest date last)',
    nextSessionFirst: 'Next Session Date(nearest date first)',
    lengthHighest: 'Length(highest first)',
    lengthLowest: 'Length(lowest first)',
    nextSessionDate:'Next Session Date:',
    courseLink: 'Course Link',
    videoLink: 'Video Link',
    length: 'Length: ',
    SET_API_DATA: 'SET_API_DATA',
    SET_PROVIDER_LIST_DATA: 'SET_PROVIDER_LIST_DATA',
    SET_UNIVERSITY_LIST_DATA: 'SET_UNIVERSITY_LIST_DATA',
    SET_SUBJECT_LIST_DATA: 'SET_SUBJECT_LIST_DATA',
    SET_CHILD_SUBJECT_LIST_DATA: 'SET_CHILD_SUBJECT_LIST_DATA',
    SET_FILTERED_ARRAY: 'SET_FILTERED_ARRAY',
    SET_TOTAL_COURSE_FOUND: 'SET_TOTAL_COURSE_FOUND',
    SET_USER_COURSE_FOUND: 'SET_USER_COURSE_FOUND',
};
export default Constants;
